---
title: "Lamb, Rosemary and Garlic Pie"

date: 2023-10-28
categories: [lamb, dinner]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Lamb, Rosemary and Garlic Pie


## Ingredients

* 1 tbsp olive oil
* 500g diced lamb
* 1 tbsp olive oil extra
* &frac12; red onion
* 2 tsp. crushed garlic
* 250g potatoes
* 1 carrot
* &frac14; cup peas
* &frac14; cup tomato paste
* &frac16; cup gravy powder
* 1 &frac12; cups water
* 1 &frac12; tsp. beef stock powder
* 1 tbsp worcestershiresauce
* 1 tbsp fresh rosemary
* 1 tbsp cornflour
* 2 tbsp warm water
* 2 sheets puff pastry
* 1 egg


## Method

Heat oil in frypan and add the lamb. Cook until well browned. Remove from pan.

Add extra oil and add sliced onion and garlic. Cook until soft. Cube potatoes and carrots. Add to pan cook stirring for 5 minutes or until browned. Add peas, tomato paste, stock powder and gravy powder. Cook stirring for 1 minute.

Return lamb to pan. Add water and worcestershire sauce. Bring to the boil. Reduce heat and simmer covered for 2 hours. Stir in rosemary and season with salt and pepper.
Combine water and cornflour. Add to lamb simmer 1 minute. Cool. 

Preheat oven to 200 degrees. Lightly grease pie dishes. Fill pie case with lamb mixture. Place remaining sheet of pastry over pie. Press edges with a fork to seal. Prick top of pastry and brush with a beaten egg. Place on a baking tray and bake for 25–30 mins. Serve.