project:
  type: website
  output-dir: docs

website:
  title: "Michael Lydeamore"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: recipes/index.qmd
        text: Recipes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
