---
title: "Curriculum Vitae"
format:
    html:
        toc: true
        page-layout: full
        include-after-body: 
            text: |
                <script src="../assets/aos.js"></script>
                <script>
                AOS.init({
                anchorPlacement: 'top-left',
                duration: 1000,
                offset: 120
                });
                </script>
css: assets/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
michael.lydeamore@monash.edu
:::

::: {.aos-init .aos-animate}

## <i class="bi bi-briefcase-fill"></i> Appointments Held

**Senior Lecturer -- Econometrics and Business Statistics** <br> *Monash University* [*2021 ---*]{.cvdate}

**COVID-19 Modelling & Forecasting Lead <br>Manager, Analytics**<br> *Department of Health and Human Services, Victoria* [*2020*]{.cvdate}

**Postdoctoral Research Fellow**<br> *Monash University* [*2019 --- 2021*]{.cvdate}

**Honorary Team Member**<br> *SaferCare Victoria* [*2019 ---*]{.cvdate}

**Honorary Research Fellow**<br> *The Alfred Hospital* [*2019 ---*]{.cvdate}

**Research Fellow**<br> *The Kirby Institute* [*2018 --- 2019*]{.cvdate}

:::

::: {.aos-init .aos-animate aos="zoom-out-right"}

## <i class="bi bi-mortarboard-fill"></i> Education

**Doctor of Philosophy -- Applied Mathematics** <br> *The University of Melbourne* [*2015 --- 2019*]{.cvdate}

Thesis title: Mechanistic and statistical models of skin disease transmission

**Masters of Philosophy -- Applied Mathematics** <br> *The University of Adelaide* [*2013 --- 2014*]{.cvdate}

Thesis title:  Approximations of stochastic household models for comparing antiviral allocation schemes.

Awarded the Applied Probability Trust prize for the highest mark with a project in Applied Mathematics and Statistics

**Bachelor of Mathematical Sciences** <br> *The University of Adelaide* [*2010 --- 2012*]{.cvdate}

Graduated with a double major in applied and pure mathematics

:::

## <i class="bi bi-journals"></i> Publications

### 2024
**Estimating the impact of test-trace-isolate-quarantine systems on SARS-CoV-2 transmission in Australia** <br> *Epidemics*
<br>
[Shearer, F.M., McCaw, J.M., Ryan, G.E., Hao, T., Tierney, N.J., **Lydeamore, M.J.**, Wu, L., Ward, K., Ellis, S., Wood, J., McVernon, J., Golding, G.
<br>
DOI: [10.1016/j.epidem.2024.100764](https://doi.org/10.1016/j.epidem.2024.100764)]{.smaller}

### 2023

**COVID-19 vaccine coverage targets to inform reopening plans in a low incidence setting** <br> *Proceedings of the Royal Society: Series B*
<br>
[Conway, E., Walker, C.R., Baker, C., **Lydeamore, M.J.**, Ryan, G.E., Campbell, T., Miller, J.C., Rebuli, N., Yeung, M., Kabashima, G., Geard, N., Wood, J., McCaw, J.M., McVernon, J., Golding, N., Price, D.J., Shearer, F.M.
<br>
DOI: [10.1098/rspb.2023.1437](https://doi.org/10.1098/rspb.2023.1437)]{.smaller}

**The incidence of nosocmial bloodstream infection and urinary tract infection in Australian hospitals before and during the COVID-19 pandemic: an interrupted time series study** <br> *Antimicrobial Resistance and Infection Control*
<br>
[Mitchell, B.G., Stewardson, A.J., Kerr, L, Ferguson, J.K., Curtis, S., Busija, Ljoudmila, **Lydeamore, M.J.**, Graham, K., Russo, P.L.
<br>
DOI: [10.1101/2021.10.05.21264587](https://doi.org/10.1186/s13756-023-01268-2)]{.smaller}


### 2022

**Burden of five healthcare associated infections in Australia** <br> *Antimicrobial Resistance and Infection Control*
<br>
[**Lydeamore, M. J.**, Mitchell, B. G., Bucknall, T., Cheng, A.C., Russo, P. L., Stewardson, A. J.
<br>
DOI: [10.1101/2021.10.05.21264587](https://doi.org/10.1186/s13756-022-01109-8)]{.smaller}

**COVID-19 in low-tolerance border quarantine systems: impact of the Delta variant of SARS-CoV-2** <br> *Science Advances*
<br>
[Zachreson, C., Sharer, F. M., Price, D. J., **Lydeamore, M. J.**, McVernon, J., McCaw, J., Geard, N. G.
<br>
DOI: [10.1126/sciadv.abm3624](https://doi.org/10.1126/sciadv.abm3624)]{.smaller}

### 2021
**Population-based analysis of the epidemiological features of COVID-19 epidemics in Victoria, Australia, January 2020-March 2021, and their suppression through comprehensive control strategies** <br> *Lancet Regional Health --- Western Pacific*
<br>
[Sullivan, S. G., Brotherton, M. L., Lynch, B. M., Cheung, A. **Lydeamore, M.J.**, Stevenson, M., Firestone, S., Canevari, J., Nguyen, H.N.J., Carville, S., Clothier, H.J., \dots, Sutton, B., Rowe, S. L.
<br>
DOI: [10.1016/j.lanwpc.2021.100297](https://doi.org/10.1016/j.lanwpc.2021.100297)]{.smaller}

**Mathematical models to support Victoria's COVID-19 response: a blunt instrument to a complex problem** <br> *AustMS Journal*
<br>
[**Lydeamore, M.J.**]{.smaller}

**Understanding how Victoria, Australia gained control of its second COVID-19 wave** <br> *Nature Communications*
<br>
[Trauer, J.M., **Lydeamore, M. J.**, Dalton, G. W., Meehan, M.T., McBryde, E. S., Cheng, A. C., Sutton, B., Ragonnet, R.
<br>
DOI: [10.1038/s41467-021-26558-4](https://doi.org/10.1038/s41467-021-26558-4)]{.smaller}

**Risk mapping for COVID-19 outbreaks in Australia using mobility data** <br> *Royal Society: Interface*
<br>
[Zachreson, C., Mitchell, L., **Lydeamore, M. J.**, Rebuli, N., Tomko, M., Geard, N.
<br>
DOI: [10.1098/rsif.2020.0657](https://doi.org/10.1098/rsif.2020.0657)]{.smaller}

### 2020

**Estimation of the force of infection and infectious period of skin sores in remote Australian communities using interval-censored data** <br> *PLoS Computational Biology*
<br>
[**Lydeamore, M. J.**, Campbell, P.T., Price, D.J., Wu,Y., Marcato, A.J., Cuningham, W., Carapetis, J.R., Andrews, R.M., McDonald, M.I., McVernon, J., Tong, S.Y.C., McCaw, J.M.
<br>
DOI: [10.1371/journal.pcbi.1007838](https://doi.org/10.1371/journal.pcbi.1007838)]{.smaller}

### 2019

**A biological model of scabies infection dynamics and treatment informs mass drug administration strategies to increase the likelihood of elimination** <br> *Mathematical Biosciences*
<br>
[**Lydeamore, M. J.**, Campbell, P. T., Regan, D.G., Tong, S., Andrews, R., Steer, A.C., Romani, L., Kaldor, J., McVernon, J., McCaw, J.M.
<br>
DOI: [10.1016/j.mbs.2018.08.007](https://doi.org/10.1016/j.mbs.2018.08.007)]{.smaller}

**High Burden if Infectious Disease and Antibiotic Use in Early Life in Aboriginal Communities** <br> *Australia and New Zealand Journal of Public Health*
<br>
[Cuningham, W., McVernon, J., **Lydeamore, M. J.**, Andrews, R. M., Carapetis, J., Kearns, T., Clucas, D., Gundjirryirr Dhurrkay, R., Tong, S. Y. C., Campbell, P. T.
<br>
DOI: [10.1111/1753-6405.12876](https://doi.org/10.1111/1753-6405.12876)]{.smaller}

### 2018

**Calculation of the age of first infection for skins sores and scabies in five remote communities in northern Australia** <br> *Epidemiology & Infection*
[**Lydeamore, M. J.**, Campbell, P. T., Cuningham, W., Andrews, R., Kearns, T., Clucas, D., Gundjirryirr Dhurrkay, R., Carapetis, J., Tong, S. Y. C., McCaw, J. M., McVernon, J.
<br>
DOI: [10.1017/S0950268818001061](https://doi.org/10.1017/S0950268818001061)]{.smaller}

### 2017

**Indigenous Australia household structure --- implications for close contact transmission of communicable diseases** <br> *PeerJ*
[Vino, T., Davison, B., Campbell, P. T., **Lydeamore, M. J.**, McVernon, J., Singh, G., Tong, S. Y. C., Robinson, A., Geard, N.
<br>
DOI: [10.7717/peerj.3958](https://doi.org/10.7717/peerj.3958)]{.smaller}

### 2016

**Choice of antiviral allocation scheme for pandemic influenza depends on strain transmissibility, delivery delay and stockpile size** <br> *Bulletin of Mathematical Biology*
[**Lydeamore, M.**, Bean, N., Black, A. J., Ross, J. V.
<br>
DOI: [10.1007/s11538-016-0144-6](http://doi.org/10.1007/s11538-016-0144-6)]{.smaller}

## <i class="bi bi-cash-stack"></i> Funding

Almost all of this funding was obtained in partnership with large, collaborative teams.

**Contractual Partner to Conduct Research on Healthcare-Associated Infection Rates in Phillippine Hospitals** <br> *World Health Organisation Phillippines* [*2023*]{.cvdate}<br>
Awarded value: $72,078

**Centre of Western Public Health Unit** <br> *Contract Research* [*2023*]{.cvdate}<br>
Awarded value: $25,000

**Extending and comparing methods for projecting social contact matrices** <br> *SPECTRUM/SPARK Seed Funding* [*2022*]{.cvdate}<br>
Awarded value: $19,438

**Quantifying longitudinal relationships between community mobility and COVID-19 case incidence in west metropolitan Melbourne** <br> *SPECTRUM/SPARK Seed Funding* [*2022*]{.cvdate}<br>
Awarded value: $19,896

**Modelling to support Australia's national plan for COVID-19** <br> *Commonwealth Government of Australia* [*2021*]{.cvdate}<br>
Awarded value: $147,536

**Modelling to support Australia's transition to 'COVID-normal'**<br> *Australian Office of Health Protection* [*2021*]{.cvdate}<br>
Awarded value: $25,620

## <i class="bi bi-chat-quote"></i> Conference presentations and contributed talks

**Data-Driven Insights into Healthcare Challenges: Two Case Studies**<br> *UNSW Australia Statistics & Data Science Seminar* [*2023*]{.cvdate}

**Burden of healthcare associated infections in Australia**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2022*]{.cvdate}

**Exponential Random Graph Models and CPE transmission**<br> *Melbourne Mathematical Biology Seminar Series --- Invited Speaker* [*2021*]{.cvdate}

**Mathematical modelling for COVID-19 in Victoria, Australia**<br> *Math for Industry Forum, Vietnam --- Invited Speaker* [*2021*]{.cvdate}

**The associations between transmission of CPE and ward connectivity: a network analysis**<br> *Australasian Society for Infectious Diseases Annual Scientific Meeting* [*2021*]{.cvdate}

**The burden of healthcare acquired infections in Australian public hospitals**<br> *Australasian Society for Infectious Diseases Annual Scientific Meeting* [*2021*]{.cvdate}

**Decision Making and Mathematical Biology - Victoria's usage of COVID-19 modelling**<br> *Mathematical Biology Special Interest Group Workshop - Invited Speaker* [*2021*]{.cvdate}

**Modelling between-household effective contact and the elimination of COVID-19 in Melbourne, Australia**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2021*]{.cvdate}

**Mathematical modelling and Victoria's response to COVID-19**<br> *Victorian ANZIAM Branch Meeting --- Invited Speaker* [*2020*]{.cvdate}

**Australia's experience and the role of modelling in its responses to COVID-19**<br> *Usher Institute COVID-19 Webinar --- Invited Speaker* [*2020*]{.cvdate}

**Estimating epidemiological quantities for skin sores in remote Australian communities using interval-censored data**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2019*]{.cvdate}

**Estimating epidemiological quantities for skin sores in remote Australian communities using interval-censored data**<br> *NSW--ACT ANZIAM Branch Meeting* [*2018*]{.cvdate}

**Coupled models of Group A Streptococcus and Scabies: How likely is eradication?**<br> *PRISM International Conference* [*2018*]{.cvdate}

**Investigating the dynamics of coupled epidemiological transmission models with application to Group A Streptococcus and Scabies**<br> *Society for Mathematical Biology Annual Meeting* [*2018*]{.cvdate}

**Investigating the dynamics of coupled models with applications to Group A Streptococcus and Scabies**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2018*]{.cvdate}

**Quantifying the age of first infection with skin sores in five remote Australian Aboriginal communities**<br> *Lancefield International Symposium on Streptococci and Streptococcal Diseases* [*2017*]{.cvdate}

**Investigating the dynamics of coupled models with applications to Group A Streptococcus and Scabies**<br> *PRISM Annual Knowledge Transfer and Training Conference* [*2017*]{.cvdate}

**Constructing mathematical models of Group A Streptococcus and Scabies in remote Australian Indigenous communities**<br> *Zeeman Institute Seminar Series --- Invited Speaker* [*2017*]{.cvdate}

**Developing a model for the transmission and treatment dynamics of scabies infections a high prevalence setting**<br> *Melbourne-Manchester Joint Workshop* [*2017*]{.cvdate}

**Developing a model for the transmission of Group A Streptococcus**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2017*]{.cvdate}

**Determining the age of first infection from incomplete data**<br> *Modelling Emerging Infections and Neglected Tropical Diseases Workhop* [*2016*]{.cvdate}

**Investigating Intervention Intervals for Scabies Infections**<br> *Australia and New Zealand Industrial Applied Mathematics Conference* [*2016*]{.cvdate}

## <i class="bi bi-building"></i> Teaching

### Lecturer

[ETC5513] **Reproducible and Collaborative practices** (Chief Examiner) [*2024--*]{.cvdate}

[ETC5523] **Communicating With Data** (Chief Examiner) [*2023--*]{.cvdate}

[ETC5512] **Wild-Caught Data** [*2022, 2023*]{.cvdate}

[ETC5521] **Exploratory Data Analysis** [*2022*]{.cvdate}

### Tutor

[MAST10016] **Mathematics for BioMedicine** [*2016--2019*]{.cvdate}

[MAST30001] **Stochastic Modelling** [*2018*]{.cvdate}

## <i class="bi bi-award"></i> Awards

**University of Melbourne Faculty of Engineering and Information Technology Excellence Award in Interdisciplinary Research** [*2021*]{.cvdate}

**IPAA Spirit of Service Awards** -- Finalist [*2021*]{.cvdate}

**Engagement Australia Excellence Awards --- Outstanding Engagement for Research Impact** --- Finalist [*2021*]{.cvdate}

**Top Poster Award --- European Congress of Clinical Microbiology \& Infectious Diseases** [*2021*]{.cvdate}

**IPAA Victoria Leadership in the Public Sector Awards** --- Finalist [*2021*]{.cvdate}

**Best PhD Student Presentation -- PRISM$^2$ Annual Conference** [*2017*]{.cvdate}

**Applied Probability Trust Prize** for best Applied Mathematics Postgraduate Thesis [*2016*]{.cvdate}

**Australian Postgraduate Award** [*2015*]{.cvdate}

**Dean's Commendation for Thesis Excellence** [*2015*]{.cvdate}

## <i class="bi bi-person-workspace"></i> Academic Service & Community Engagment

**SPARK Short Course in Mathematical Diseases Modelling --- OUCRU**<br>
Facilitator [*2023*]{.cvdate}

**Maths in Industry Study Group --- NSW Health**<br>
Moderator [*2023*]{.cvdate}

**Communicating with Data Workshop**<br>
Organising Committee [*2023*]{.cvdate}

**Australian & New Zealand Industrial Applied Mathematics Executive Committee**<br>
Treasurer [*2022 --*]{.cvdate}<br>
Early Career Representative [*2021--2022*]{.cvdate}

**SPECTRUM-SPARK Early Career Researcher Committee**<br>
Chair [*2022 --*]{.cvdate}

**SPARK Short Course in Mathematical Diseases Modelling - Mahidol University**<br>
Facilitator [*2022*]{.cvdate}

**Research Tools Workshop in R**<br>
Facilitator [*2022*]{.cvdate}

**Mathematical Biology Special Interest Group**<br>
Treasurer [*2019--2022*]{.cvdate}

**ANZIAM 2021 Conference**<br>
Organising committee --- Treasurer [*2020--2021*]{.cvdate}

**Computational Biology Research Initiative -- The University of Melbourne**<br>
Postgraduate Representative [*2017*]{.cvdate}

**Computational Biology Postgraduate Sports Group -- The University of Melbourne**<br>
Secretary [*2017--2018*]{.cvdate}

**Mathematics in Industry Study Group**<br>
Participant [*2017, 2018, 2019*]{.cvdate}

**The ConocoPhilips Science Experience -- The University of Melbourne**<br>
Activity Organiser [*2016--2018*]{.cvdate}

**Mathematicians in Schools**<br>
Project Supervisor/Mentor [*2016--2018*]{.cvdate}

**Reviewer**<br>
PLoS Comptuational Biology; Scientific Reports; Journal of Applied Mathematics; Journal of Statistical Software; Epidemiology \& Infection; Mathematics; Medial Journal of Australia; International Tropical Health; Journal of Antimicrobial Resistance; The R Journal

## <i class="bi bi-person-badge"></i> Professional Memberships

**Australia and New Zealand Industrial and Applied Mathematics** [*2015--*]{.cvdate}<br>
Including the Mathematical Biology Special Interest Group

**Australian Mathematics Society** [*2015--*]{.cvdate}