---
title: "Mushroom Buckwheat Risotto"

date: 2022-12-18
categories: [lunch, keto]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Mushroom Buckwheat Risotto

Yet another Keto meal to try and distract you from the fact you're on a Keto diet.

## Ingredients

* 1/3 cup raw buckwheat
* 1/2 onion
* 1 clove garlic
* 2 cups hot vegetable stock
* 1/2 cup white wine
* 1/3 cup dried shiitake mushrooms
* 2 large portobello mushrooms
* 2 tbsp thyme
* 2 tbsp oregano
* 1/2 cup chopped parsley
* 2 tbsp olive oil
* 1/3 cup grated parmesan
* Large spoon of creamy chevre
* Salt & pepper


## Method

Put shiitake mushrooms in 1/3 cup boiling water and leave to infuse. Heat up the stock. Saute onion and garlic in olive oil. Add buckwheat and stir for 2-3 minutes. Add wine, once absorbed start adding stock, one ladel at a time. Add shiitake mushrooms. 

Fry portobello mushrooms in oil with oregano & thyme (10-15 minutes).

Add parsley, parmesan & liquid from shiitake to buckwheat. Add salt and pepper, let stand for 2 minutse. Add portobello. Serve with goats cheese.
