---
title: "Pork and Bean Burrito Bowl"

date: today
categories: [low fat, pork]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Pork and Bean Burrito Bowl



## Ingredients

- 3 tsp extra virgin olive oil
- 1 red onion, finely chopped
- 2 garlic cloves, crushed
- 1 tsp cumin seeds
- 425g can black beans, rinsed, drained
- 3 vine-ripened tomatoes, finely chopped
- 1 lime, rind finely grated, juiced
- 1 tsp dried chilli flakes
- 4 (120g each) lean pork loin steaks, fat trimmed
- 200g cabbage, finely shredded
- 60g baby spinach leaves, thinly sliced
- 1 large carrot, peeled, coarsely grated
- &frac12; cup fresh coriander leaves, coarsely chopped, plus extra to serve
- 1 tsp honey
- &frac12; small avocado, sliced
- 70g (&frac14; cup) natural yoghurt
- Lime wedges, to serve

## Method

Heat 1 tsp oil in a saucepan over medium heat. Add onion. Cook, stirring, for 5 minutes or until softened. Add garlic and cumin. Cook, stirring, for 1 minute. Add beans and tomato. Cook, stirring, for 8-10 minutes, until thickened.

Meanwhile, heat a chargrill pan over high heat. Combine rind, &frac12; tsp chilli, and a large pinch of sea salt in a bowl. Rub over the pork. Spray with olive oil. Cook for 3-4 minutes each side or until the pork is just cooked through. Transfer to a plate. Cover loosely with foil. Set aside for 5 minutes to rest. Thickly slice.

Combine the cabbage, spinach, carrot, and coriander in a large bowl. Whisk the honey, 1 tablespoon juice, and remaining oil and chilli in a small bowl. Add to slaw. Toss to combine.

Divide the slaw among bowls. Top with the bean mixture, pork, and avocado. Serve with yoghurt, extra lime wedges, and coriander.
