---
title: "Pumpkin Macaroni Cheese"

date: 2023-05-06
categories: [dinner, pasta, pumpkin]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Pumpkin Macaroni Cheese

Uses a boatload of pumpkin with a boatload of nicely caramlised cheese.

## Ingredients

* 2 1&frasl;2 cups pumpkin (500g) chopped
* 2 tablespoons oil
* 1 teaspoon salt
* 1 teaspoon pepper
* 1 teaspoon dried sage

#### Sauce

* 40g butter
* 40g flour
* 2 1&frasl;2 cups milk
* 1&frasl;4 tsp nutmeg
* 1 teaspoon garlic powder
* 1 teaspoon pepper
* 200g cheddar cheese
* 25g parmesan cheese
* 250g macaroni pasta, cooked and drained


#### Topping

* 50g cheddar cheese
* 50g mozzarella cheese
* 25g parmesan cheese

## Method

Preheat the oven to 190°C.

Chop up the pumpkin into chunks and place on a baking tray. Drizzle over the oil, salt, pepper, and ground sage, and coat evenly with your hands. Roast in the oven for 20 minutes. Once cooked leave to cool slightly and blend 1&frasl;3 of the pumpkin, set aside.

For the sauce, in a large ovenproof pan, melt the butter over a medium-low heat.
Gradually mix in the flour to create a roux.
Add the milk in 4-5 parts stirring well in between.
Continue to stir and cook the sauce for a further 5-10 minutes or until the sauce is simmering and thickened.
Stir in the ground nutmeg, garlic powder, pepper, cheddar, and Parmesan.
Stir in the blended pumpkin.
Stir in the remaining whole pumpkin and macaroni, mix until combined.
Top with the cheddar, mozzarella, and Parmesan.

Grill for 10 minutes at 200°C (400°F) until the cheese is brown and bubbling.