---
title: "Bacon-wrapped cauliflower"

date: 2022-12-18
categories: [lunch, keto]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Bacon-wrapped cauliflower

Yet another Keto meal to try and distract you from the fact you're on a Keto diet.

## Ingredients

* 1/4 cup oil
* 1/4 cup lemon juice
* 1 cauliflower
* 2 eggs, beaten
* 4 spring onions
* 2 cloves garlic, minced
* 3/4 cup shredded cheese
* 125g cream cheese
* 1/2 cup breadcrumbs
* 1/4 cup parmesan cheese
* 500g bacon
* 250g frozen chopped spinach.


## Method

Boil 8 cups of water, oil, lemon juice and tbsp of salt in a large pot. Add cauliflower, weigh down with plate. Boil for 12 minutes and let cool. 

Combine spinach, eggs, spring onions, crushed garlic, cheese, cream cheese, breadcrumbs and parmesan. Put in piping bag. Turn cauliflower upside down and pipe filling (get the muscles out). Turn cauliflower back over and wrap in bacon. You may need to hold in place with toothpicks. 

Roast for 30 minutes at 230C.
