---
title: "Pumpkin and Goat's Cheese Tart"

date: 2023-05-19
categories: [dinner, pumpkin, pastry]
format:
    html:
        highlight: default
        toc: true
        toc_float: true
---

# Pumpkin and Goat's Cheese Tart

Makes two tarts, both of which are tasty. Best fresh, reheating is more questionable.

## Ingredients

* 2 sheets shortcrust pastry
* 650g pumpkin
* 150g goat's cheese
* 2 tbsp thyme
* 4 eggs
* 200g diced bacon
* 2 tbsp maple syrup
* 160mL thickened cream
* 180mL milk


## Method

Preheat oven to 200C. Lightly grease tart tin and line with pastry. Place in oven for 15 minutes, and cool. Press down with your hands to fully flatten the base.

Cook bacon and maple syrup and let cool.

Slice pumpkin into very thin slices. Spread bacon mixture onto base. Starting from the outside and working your way in, arrange pumpkin into pastry shell in a rosette pattern.

Scatter small/cubed bits of goat's cheese and use some to wedge between some of the slices to separate slightly. Sprinkle with thyme.

Reduce oven to 170C. Whisk together egg, cream and milk. Pour over pumpkin and bake for 30 minutes, or until set.